name: tro_moi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  lottie: ^2.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
